function [] = CM_setguidata(selch, appDesDataTable, info, Vrange)   
%{
    Input Parameters: 
    appDesDataTable - data table in app designer
    info        - processed.info, 4 * 17 table
    Vrange      - [parameters.Vrange parameters.Vrange_cathodal [1*88, 1*87]

    Displays performance metrics, and info generated by calcdata.
%}


% plots data horizontally
for ii = selch

    % true for 1 - 4
    if ~isempty(info(ii).VmaxID)

        % false for 1 -4
        if info(ii).noise==0
            info(ii).noise=100;
        end
        
        tableArray(ii, 1) = string(['channel = ' num2str(ii)]);
        tableArray(ii, 2) = string(['n_' num2str(ii) '(t) = ' num2str(round(info(ii).noise*1000)/1000) ' nA']);
        tableArray(ii, 3) = string(['snr_' num2str(ii) ' = ' num2str(info(ii).snr)]);     
        

        % VmaxID (index) greater than or equal to length of Vrange
        if info(ii).VmaxID>=length(Vrange)
            Vmax=0;
        % use VmaxID to index into Vrange vector and return a value
        else
            Vmax=Vrange(info(ii).VmaxID);
        end

        Vmax=Vmax(1);

        tableArray(ii, 4) =  string(['E_o_x_' num2str(ii) ' = ' num2str(round(Vmax*100)/100) ' V']);                      
        tableArray(ii, 5) =  string(['I_o_x_' num2str(ii) ' = ' num2str(round(info(ii).Imax*100)/100) ' nA']);            
        tableArray(ii, 6) =  string(['Iabs' num2str(ii) ' = ' num2str(round(info(ii).Iabs*100)/100) ' nA']);             
        tableArray(ii, 7) =  string(['T_1_/_2' num2str(ii) ' = ' num2str(round(info(ii).thalfSamples*1000)/10) ' ms']);  
        tableArray(ii, 8) =  string(['R' num2str(ii) ' = ' num2str(round(max(info(ii).R)*100)/100)]);                     
        tableArray(ii, 9) =  string(['Q' num2str(ii) ' = ' num2str(round(info(ii).Q)*100/100)]);                          
        tableArray(ii, 10) = string(['RPH' num2str(ii) ' = ' num2str(round(max(info(ii).RPH)*100)/100)]);                
        tableArray(ii, 11) = string(['RBG' num2str(ii) ' = ' num2str(round(max(info(ii).RBG)*100)/100)]);              
        tableArray(ii, 12) = string(['RM' num2str(ii) ' = ' num2str(round(max(info(ii).RM)*100)/100)]);                
        
        % false
        if isfield(info,'behav')
            tableArray(ii, 13) = string(['RT target' num2str(ii) ' = ' num2str(round(info(ii).behav.target_rt*1000)) 'ms']);      
            tableArray(ii, 14) = string(['RT fix' num2str(ii) ' = ' num2str(round(info(ii).behav.fix_rt*1000)) 'ms']);            
            tableArray(ii, 15) = string(['Current side' num2str(ii) ' = ' info(ii).behav.currside]);             

            if isfield(info(ii).behav,'currbigside')
                tableArray(ii, 16) = string(['Big side' num2str(ii) ' = ' info(ii).behav.currbigside]);
            else
                tableArray(ii, 16) = "";
            end            
        end        
    end
end

% assignin('base','tableInfo', tableArray);

appDesDataTable.Data = tableArray(selch, :)';

end
